;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-delete-region
        cua-paste
        cua-set-rectangle-mark
        ido-find-file
        nxml-electric-slash
        org-force-self-insert
        orgtbl-hijacker-command-100
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        yaml-electric-backspace
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        compile-goto-error
        mark-whole-buffer
        python-shell-send-buffer
        yaml-electric-backspace
        ))
